AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  airfoils-online

  Sample SAM Template for airfoils-online

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  NACA4AirfoilFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: NACA4Airfoil/lambda/
      Handler: app.lambda_handler
      Layers:
        - !Ref NACA4AirfoilLayer
      Runtime: python3.11
      Architectures:
      - x86_64
      Timeout: 10
      Events:
        NACA4Airfoil:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /NACA4Airfoil
            Method: get
  NACA4AirfoilLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: naca-dependencies
      Description: Dependencies for sam app [temp-units-conv]
      ContentUri: naca_layer/
      CompatibleRuntimes:
        - python3.11
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: python3.11

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  NACA4AirfoilApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/NACA4Airfoil/"
  NACA4AirfoilFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt NACA4AirfoilFunction.Arn
  NACA4AirfoilFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt NACA4AirfoilFunctionRole.Arn
